from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet

from mission_statistics import mission_statistics
from graficos import generate_graphs
import os
from reportlab.lib import colors
from reportlab.lib.pagesizes import landscape, A4
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
)
from reportlab.lib.styles import getSampleStyleSheet

from mission_statistics import mission_statistics
from graficos import generate_graphs

import openai

openai.api_key = "key_x6jNi46p1qF2qny7" 

def generate_ai_analysis(temp, energy):

    response = openai.ChatCompletion.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "user", "content": f"""
Analise esses dados:

Temp CV: {temp['cv']}
Temp max: {temp['maximum']}
Energy mean: {energy['mean']}

Escreva um relatório estilo NASA.
"""}
        ]
    )

    return response["choices"][0]["message"]["content"]
def generate_report():

  
    BASE_DIR = os.path.dirname(os.path.abspath(__file__))

    generate_graphs()
    stats = mission_statistics()

    temp = stats["temperature"]
    energy = stats["energy"]

    pdf = SimpleDocTemplate(
        os.path.join(BASE_DIR, "Mission_Report.pdf"),
        pagesize=landscape(A4)
    )

    styles = getSampleStyleSheet()
    elements = []

    logo_path = os.path.join(BASE_DIR, "logo_nasa.png")

    try:
        logo = Image(logo_path, width=80, height=80)

        header = Table(
            [[
                logo,
                Paragraph(
                    """
                    <b>NASA MISSION CONTROL CENTER</b><br/>
                    Telemetry Intelligence Report System<br/>
                    AI-Assisted Space Analysis
                    """,
                    styles["Title"]
                )
            ]],
            colWidths=[100, 650]
        )

        elements.append(header)

    except:
        elements.append(
            Paragraph("NASA Mission Control Center", styles["Title"])
        )

    elements.append(Spacer(1, 10))

    elements.append(Paragraph("Mission Telemetry Graphs", styles["Heading2"]))
    elements.append(Spacer(1, 5))

    graphs = Table(
        [[
            Image(os.path.join(BASE_DIR, "temperature_graph.png"), width=250, height=140),
            Image(os.path.join(BASE_DIR, "energy_graph.png"), width=250, height=140)
        ]]
    )

    elements.append(graphs)

    elements.append(Spacer(1, 10))

    temp_table = Table([
        ["TEMP METRIC", "VALUE"],
        ["Mean", temp["mean"]],
        ["Median", temp["median"]],
        ["CV", temp["cv"]],
        ["Min", temp["minimum"]],
        ["Max", temp["maximum"]],
    ])

    energy_table = Table([
        ["ENERGY METRIC", "VALUE"],
        ["Mean", energy["mean"]],
        ["Variance", energy["variance"]],
        ["Min", energy["minimum"]],
        ["Max", energy["maximum"]],
    ])

    elements.append(Table([[temp_table, energy_table]]))

    elements.append(Spacer(1, 15))

    ai_report = generate_ai_analysis(temp, energy)

    elements.append(Paragraph("AI Mission Analysis", styles["Heading2"]))
    elements.append(Spacer(1, 8))

    elements.append(
        Paragraph(ai_report.replace("\n", "<br/>"), styles["BodyText"])
    )

    elements.append(Spacer(1, 20))

    elements.append(
        Paragraph(
            "<font size=8>Generated by AI-assisted NASA telemetry system.</font>",
            styles["BodyText"]
        )
    )

    pdf.build(elements)

    print("Mission_Report.pdf generated successfully 🚀")


if __name__ == "__main__":
    generate_report()

def generate_report():

    # Gera os gráficos atualizados
    generate_graphs()

    stats = mission_statistics()

    temp = stats["temperature"]
    energy = stats["energy"]

    pdf = SimpleDocTemplate(
        "Mission_Report.pdf",
        pagesize=landscape(A4)
    )

    styles = getSampleStyleSheet()

    elements = []

    try:

        logo = Image(
            "logo_nasa.png",
            width=80,
            height=80
        )

        header = Table(
            [[
                logo,

                Paragraph(
                    """
                    <b>NASA MISSION CONTROL CENTER</b><br/>
                    Experimental Space Mission Monitoring Platform<br/>
                    Telemetry Analysis and Operational Intelligence Report
                    """,
                    styles["Title"]
                )
            ]],
            colWidths=[100, 550]
        )

        elements.append(header)

    except:

        elements.append(
            Paragraph(
                "NASA Mission Control Report",
                styles["Title"]
            )
        )

    elements.append(Spacer(1, 10))


    elements.append(
        Paragraph(
            "Executive Summary",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            """
            This technical report presents the operational analysis of an
            experimental space mission monitoring system.

            The platform continuously collects and evaluates telemetry
            information related to temperature, energy availability,
            communication performance and mission status indicators.

            The objective is to transform raw telemetry data into
            actionable operational intelligence, supporting monitoring,
            anomaly detection and decision-making during mission
            execution.
            """,
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 10))

    elements.append(
        Paragraph(
            "Mission Telemetry Graphs",
            styles["Heading2"]
        )
    )

    elements.append(Spacer(1, 5))

    graphs = Table(
        [[
            Image(
                "temperature_graph.png",
                width=250,
                height=140
            ),

            Image(
                "energy_graph.png",
                width=250,
                height=140
            )
        ]],
        colWidths=[300, 300]
    )

    graphs.setStyle(TableStyle([
        ("LEFTPADDING", (0, 0), (-1, -1), 20),
        ("RIGHTPADDING", (0, 0), (-1, -1), 20),
        ("TOPPADDING", (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE")
    ]))

    elements.append(graphs)

    elements.append(Spacer(1, 10))

    temp_table = Table([
        ["TEMPERATURE METRIC", "VALUE"],
        ["Mean", temp["mean"]],
        ["Median", temp["median"]],
        ["Mode", temp["mode"]],
        ["Minimum", temp["minimum"]],
        ["Maximum", temp["maximum"]],
        ["Std Dev", temp["std_dev"]],
        ["Variance", temp["variance"]],
        ["CV (%)", temp["cv"]],
        ["Q1", temp["q1"]],
        ["Q2", temp["q2"]],
        ["Q3", temp["q3"]],
    ])

    temp_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER")
    ]))

    energy_table = Table([
        ["ENERGY METRIC", "VALUE"],
        ["Mean", energy["mean"]],
        ["Median", energy["median"]],
        ["Mode", energy["mode"]],
        ["Minimum", energy["minimum"]],
        ["Maximum", energy["maximum"]],
        ["Std Dev", energy["std_dev"]],
        ["Variance", energy["variance"]],
        ["CV (%)", energy["cv"]],
        ["Q1", energy["q1"]],
        ["Q2", energy["q2"]],
        ["Q3", energy["q3"]],
    ])

    energy_table.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkgreen),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 1, colors.black),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER")
    ]))

    stats_tables = Table(
        [[temp_table, energy_table]],
        colWidths=[330, 330]
    )

    stats_tables.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("ALIGN", (0, 0), (-1, -1), "CENTER")
    ]))

    elements.append(stats_tables)

    elements.append(Spacer(1, 10))
    if temp["cv"] < 15:

        conclusion = f"""
        The telemetry analysis indicates a highly stable mission
        environment. Temperature fluctuations remained within expected
        operational limits, presenting a coefficient of variation of
        {temp['cv']}%.

        Energy resources demonstrated consistent availability throughout
        the monitoring period, suggesting adequate system efficiency and
        mission sustainability.

        No critical operational risks were identified during the
        analyzed interval.
        """

    elif temp["cv"] < 30:

        conclusion = """
        The mission maintained acceptable operational stability.

        Although temperature variability was observed, overall behavior
        remained compatible with standard mission parameters.

        Continuous monitoring is recommended to ensure that fluctuations
        do not evolve into operational constraints.

        Current Risk Level: MODERATE
        """

    else:

        conclusion = """
        The telemetry dataset indicates significant variability in
        mission conditions.

        Temperature oscillations exceeded desirable levels, suggesting
        the need for increased supervision and preventive actions.

        Current Risk Level: HIGH
        """

    elements.append(
        Paragraph(
            "Automatic Operational Analysis",
            styles["Heading2"]
        )
    )

    elements.append(
        Paragraph(
            conclusion,
            styles["BodyText"]
        )
    )

    elements.append(Spacer(1, 15))
    elements.append(
        Paragraph(
            """
            <font size=8>
            Generated automatically by the Intelligent Space Mission
            Monitoring System developed in Python.
            </font>
            """,
            styles["BodyText"]
        )
    )

    pdf.build(elements)

    print("Mission_Report.pdf generated successfully.")

def generate_ai_analysis(temp, energy):

    print(">>> IA FOI CHAMADA")  # DEBUG 1

    from openai import OpenAI
    client = OpenAI(api_key="SUA_API_KEY_AQUI")

    prompt = "Diga apenas: IA funcionando"

    response = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[{"role": "user", "content": prompt}]
    )

    print(">>> RESPOSTA IA:", response.choices[0].message.content)

    return response.choices[0].message.content